---
language: go
sudo: false
go: 1.3.1
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/bin:$PATH
  - ARTIFACTS_CONCURRENCY=5
  - ARTIFACTS_S3_BUCKET=meatballhat
  - ARTIFACTS_TARGET_PATHS="artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER:artifacts/$TRAVIS_COMMIT"
  - ARTIFACTS_PERMISSIONS=public-read
  - ARTIFACTS_CACHE_CONTROL='public, max-age=315360000'
  - ARTIFACTS_LOG_FORMAT=multiline
  - ARTIFACTS_DEBUG=1
before_install:
- go get github.com/meatballhat/deppy
- go get code.google.com/p/go.tools/cmd/cover
- deppy restore
- go install -a -race std
script:
- make distclean all crossbuild
- if [[ $TRAVIS_PULL_REQUEST == false ]] ; then ./deploy ; fi
- travis_retry ./install
notifications:
  -email : false